modLoader="javafml"
loaderVersion="[45,)"
license="GNU GPLv3"

issueTrackerURL="https://github.com/Ramen5914/Ramenorant/issues"

[[mods]]
modId="ramenorant"
version="${file.jarVersion}"
displayName="Ramenorant"
updateJSONURL="https://github.com/Ramen5914/Ramenorant/updates.json"
displayURL="https://github.com/Ramen5914/Ramenorant"
logoFile="ramenorant.png"
credits="Thanks to FlimsyNimsy for doing this first, somehow without mods..."
authors="Omar Rahman (Ramen5914)"
displayTest="MATCH_VERSION"

description='''
Basically ports Riot Games' VALORANT to Minecraft. This took a lot of work, you can support me over at twitch.tv/Ramen5914
'''

[[dependencies.ramenorant]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ramenorant]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ramenorant]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.1.3,)"
    ordering="NONE"
    side="BOTH"
