modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/Ramen5914/Ramenorant/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/Ramen5914/Ramenorant/main/updates.json"
displayURL="https://github.com/Ramen5914/Ramenorant"
logoFile="ramenorant.png"
credits="Thanks to FlimsyNimsy for doing this first, somehow without mods..."
authors="${mod_authors}"
displayTest="MATCH_VERSION"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.2,)"
    ordering="NONE"
    side="BOTH"
