#Initial window height
earlyWindowHeight = 480
# The rendering scale of the early window
earlyWindowFBScale = 1
#Enable forge global version checking
versionCheck = true
#Early window provider (default fmlearlywindow)
earlyWindowProvider = "fmlearlywindow"
#Initial window width
earlyWindowWidth = 854
# Start the early window as "maximized"
earlyWindowMaximized = false
#Disables Optimized DFU client-side
disableOptimizedDFU = true
#Default config path for servers
defaultConfigPath = "defaultconfigs"
#should we show the early splashscreen
splashscreen = true
#Max threads for early initialization parallelism, -1 is based on processor count
maxThreads = -1

